services:
  auto:
    build:
      context: .
      dockerfile: ./service/Dockerfile
      args:
        - UID
        - GID
        - USERNAME=docker
        - GROUPNAME=docker
    container_name: comfyui01
    environment:
      CLI_ARGS: ''
    ports:
      - '8188:8188/tcp'
    network_mode: 'host'
    volumes:
      - ./volumes/custom_nodes:/volumes/custom_nodes
      - ./volumes/input:/volumes/input
      - ./volumes/output:/volumes/output
      - ./volumes/models:/volumes/models
      - ./volumes/user:/volumes/user
    logging:
      options:
        max-size: '200k'
        max-file: '10'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
