version: '3.9'
services:
  auto:
    build:
      context: .
      dockerfile: ./service/Dockerfile
    container_name: comfyui01
    environment:
      gpus: 'all'
    ports:
      - '8188:8188/tcp'
    network_mode: 'host'
    volumes:
      - ./volumes/configs:/volumes/mount/configs
      - ./volumes/models:/ComfyUI/models
      - ./volumes/custom_node:/ComfyUI/custom_node
      - ./volumes/input:/ComfyUI/input
      - ./volumes/output:/ComfyUI/output
    logging:
      options:
        max-size: '200k'
        max-file: '10'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
