version: '3.9'
services:
  auto:
    build:
      context: .
      dockerfile: ./service/Dockerfile
    container_name: comfyui01
    ports:
      - '8188:8188/tcp'
    network_mode: 'host'
    volumes:
      - ./volumes/custom_nodes:/volumes/custom_nodes
      - ./volumes/input:/volumes/input
      - ./volumes/output:/volumes/output
      - ./volumes/models:/volumes/models
    logging:
      options:
        max-size: '200k'
        max-file: '10'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
